import asyncio
import os
import sys
from typing import Dict, Any

# Add project root to path (mubasher-deep-extract)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(PROJECT_ROOT)

# Adjust import to match the actual folder structure on disk
# Try importing from backend-core if possible, or fall back
# Maintenance/dev script, never serves traffic or signs JWTs: ChatService
# transitively imports app.core.config, whose SECRET_KEY fail-fast is a
# server-boot protection — give it a harmless local default for ad-hoc runs.
os.environ.setdefault("SECRET_KEY", "maintenance-script-local-only-never-server")
try:
    from backend_core.app.chat.chat_service import ChatService
except ImportError:
    # If running from root, it might be just 'app' if backend_core is a package
    # But usually creating a symlink or adjusting path is better.
    # Let's try appending backend-core specifically
    sys.path.append(os.path.join(PROJECT_ROOT, "backend-core"))
    from app.chat.chat_service import ChatService

# Mock LLM response with new structural tags
MOCK_LLM_RESPONSE = """
Based on the provided financial data, here is the analysis for COMI.

[BULL_CASE]
- Strong revenue growth of 25% year-over-year driven by loan portfolio expansion.
- High net interest margin compared to peers.

[BEAR_CASE]
- Potential regulatory headwinds in the banking sector.
- Currency fluctuation risks affecting foreign assets.

[FRAMEWORK]
Title: CAMELS Rating Framework
Subtitle: Banking Sector Analysis
- Capital Adequacy: Strong Tier 1 capital ratio.
- Asset Quality: Non-performing loans remain low at 2.5%.
- Management Quality: Experienced leadership team with track record.
- Earnings: Sustainable ROE of 18%.
- Liquidity: Healthy loan-to-deposit ratio.
- Sensitivity: Moderate exposure to interest rate changes.

[QUANTIFIED_DRIVERS]
- Net Interest Income: +15% - Primary revenue driver due to rate hikes.
- Non-Interest Income: +8% - Growth in fee-based services.
- Operating Expenses: +5% - Controlled cost expansion.

[LEARNING]
Title: Key Financial Concepts
- Net Interest Margin (NIM): A measure of the difference between the interest income generated by banks and the amount of interest paid out to their lenders.
- ROE: Return on Equity measures financial performance calculated by dividing net income by shareholders' equity.
"""

class MockChatService(ChatService):
    """
    Subclass to expose protected parsing methods for testing.
    """
    def test_parsing(self):
        print("🔍 Testing ChatService Parsing Logic...")
        
        # Test Framework Parsing
        framework = self._parse_framework(MOCK_LLM_RESPONSE)
        if framework and framework['title'] == "CAMELS Rating Framework" and len(framework['items']) == 6:
            print("✅ Framework Parsing: SUCCESS")
            print(f"   Title: {framework['title']}")
            print(f"   Items: {len(framework['items'])}")
        else:
            print("❌ Framework Parsing: FAILED")
            print(f"   Result: {framework}")

        # Test Drivers Parsing
        drivers = self._parse_drivers(MOCK_LLM_RESPONSE)
        if drivers and len(drivers['drivers']) == 3:
            print("✅ Drivers Parsing: SUCCESS")
            print(f"   Drivers Found: {len(drivers['drivers'])}")
            print(f"   First Driver: {drivers['drivers'][0]}")
        else:
            print("❌ Drivers Parsing: FAILED")
            print(f"   Result: {drivers}")

        # Test Learning Parsing
        learning = self._parse_learning(MOCK_LLM_RESPONSE)
        if learning and learning['title'] == "Key Financial Concepts" and len(learning['items']) == 2:
            print("✅ Learning Parsing: SUCCESS")
            print(f"   Title: {learning['title']}")
            print(f"   Items: {len(learning['items'])}")
            print(f"   First Concept: {learning['items'][0]}")
        else:
            print("❌ Learning Parsing: FAILED")
            print(f"   Result: {learning}")

async def main():
    # Initialize service (mocking connection as None since we only test pure logic)
    service = MockChatService(conn=None)
    service.test_parsing()

if __name__ == "__main__":
    asyncio.run(main())
