import master from '@/content/egx-security-master.json';
import { officialSector, type EgxOfficialSector } from '@/content/egx-official-sectors';

/**
 * THE SECURITY MASTER — listing authority for every public EGX surface.
 *
 * content/egx-security-master.json is generated by scripts/egx-security-master.mjs
 * from EGX's own registers (main + SME market, keyed by ISIN), TradingView's
 * identity view and hand-verified overrides. This module turns it into:
 *
 *   · EGX_PUBLISHABLE_SQL — the allow-list gate every public LIST/aggregate
 *     query carries (via EGX_ONLY in lib/public-data.ts): only `listed`
 *     symbols are directories, screens, peers, sectors or sitemap entries.
 *     Fail-CLOSED: a symbol the master has never seen is not published until
 *     the master is regenerated — a price vendor returning data is not a
 *     listing (GTHE, delisted 2019, was served as an EGX stock for months).
 *   · getSecurity() — the status, segment, official sector and evidence a
 *     company page shows, so a non-listed symbol stays reachable with an
 *     honest notice instead of a live-looking quote.
 */
export type ListingStatus = 'listed' | 'delisted' | 'duplicate_alias' | 'rights' | 'preferred' | 'index' | 'unverified';

export type Security = {
    symbol: string;
    isin: string | null;
    name_en: string;
    name_ar: string | null;
    official_name_en: string | null;
    listing_status: ListingStatus;
    market_segment: 'main' | 'sme' | null;
    security_type: string;
    official_sector_en: string | null;
    listing_date: string | null;
    delisting_date: string | null;
    identity_source: string;
    listing_source: string | null;
    price_source: string;
    price_served_by_vendor: boolean;
    canonical_symbol: string | null;
    reason: string | null;
    evidence: string[];
    verified_at: string;
};

type Master = {
    generated_at: string;
    sources: Record<string, { url: string; captured_at: string; rows: number }>;
    counts: Record<string, number>;
    publishable_symbols: string[];
    securities: Security[];
};

const MASTER = master as unknown as Master;
const bySymbol = new Map<string, Security>(MASTER.securities.map((s) => [s.symbol.toUpperCase(), s]));

export const SECURITY_MASTER_GENERATED_AT = MASTER.generated_at;
export const SECURITY_MASTER_SOURCES = MASTER.sources;
export const PUBLISHABLE_SYMBOLS: readonly string[] = MASTER.publishable_symbols;

/** Lookup by platform symbol; null when the master has never seen it (→ unverified). */
export function getSecurity(symbol: string): Security | null {
    return bySymbol.get(symbol.toUpperCase()) ?? null;
}

/** The status the public layer acts on. Unknown symbols are unverified by construction. */
export function listingStatus(symbol: string): ListingStatus {
    return getSecurity(symbol)?.listing_status ?? 'unverified';
}

export function isPublishable(symbol: string): boolean {
    return listingStatus(symbol) === 'listed';
}

/** EGX's own sector for a listed company (EN/AR), or null when the register has none. */
export function officialSectorOf(symbol: string): EgxOfficialSector | null {
    return officialSector(getSecurity(symbol)?.official_sector_en);
}

// Symbols are validated at load: only the safe ticker alphabet may ever be
// interpolated into SQL. The master is generated from our own fixtures, but a
// gate that trusts its input is not a gate.
const SAFE = /^[A-Z0-9][A-Z0-9.\-]{0,23}$/;
for (const s of PUBLISHABLE_SYMBOLS) {
    if (!SAFE.test(s)) throw new Error(`[security-master] unsafe symbol in master: ${JSON.stringify(s)}`);
}
if (PUBLISHABLE_SYMBOLS.length < 200) {
    // A master that shrank to nothing would blank the whole company tree; that
    // is a build-time error, not a quiet empty site.
    throw new Error(`[security-master] only ${PUBLISHABLE_SYMBOLS.length} publishable symbols — refusing to gate the site on a truncated master`);
}

/**
 * SQL predicate: `symbol` is an EGX-coded row on the publish allow-list.
 * Every value passed the SAFE alphabet above, so plain quoting is exact.
 */
export const EGX_PUBLISHABLE_SQL = `market_code = 'EGX' AND symbol IN (${PUBLISHABLE_SYMBOLS.map((s) => `'${s}'`).join(',')})`;
